### ISSUE TITLE
Search filter functionality

### ISSUE THREAD

**Issue by CarmeloB4** [pc-codingavision/palermo-fe-final-project#136]
Create a functionality filter for SearchBar component

**Comment by pc-codingavision** [comment]
@CarmeloB4, @CosNig e @Matteo-Oliva ma questo task non e' stato gia' mergiato?

**Comment by CosNig** [comment]
Sì, Piero. Questa, se non erro, è la prima iterazione che avevamo creato. Quella con i vari  input e output, per intenderci. Poi, a seguito della discussione che abbiamo avuto insieme, siamo passati alla seconda iterazione, utilizzando il Subject. In effetti, questa non serve più.

**Comment by pc-codingavision** [comment]
> Sì, Piero. Questa, se non erro, è la prima iterazione che avevamo creato. Quella con i vari input e output, per intenderci. Poi, a seguito della discussione che abbiamo avuto insieme, siamo passati alla seconda iterazione, utilizzando il Subject. In effetti, questa non serve più.

Ok grazie @CosNig :)
